- README.md
I've addes a wee bit on how to edit your .htaccess file
> Subdirectory and Apache

- README.md
- includes/functions.php
- includes/rest/class-webfinger.php
- languages/activitypub.pot
- readme.txt
- templates/settings-page.php
Basic proofread, correcting various typos and cleaning up capitalisation.
> Initial proofread

- includes/class-admin.php
- includes/model/class-post.php
- templates/settings.php
This allows for posts that include only the title (no post body at all) and the link to the blog post
> Added new post type: "title and link only"

- includes/rest/class-inbox.php
Just a quick improvement to avoid actually updating the database option. I didn't test this, though, please give it a quick test.
> Code Style: Filter option in favor of updating the database

- includes/class-signature.php
- includes/functions.php
- includes/rest/class-inbox.php
adds a digest header
Mastodon now returns 202, instead of Digest missing error. 
Not sure if there is another issue, or something wrong with my setup...
#104
> add digest header

- activitypub.php
- integration/class-buddypress.php
- templates/author-json.php
fix #122
thanks and props @skysarwer
> Add basic BuddyPress support

- activitypub.php
A useful link from plugin page to settings page
> add settings link to plugin page

- docker-compose.yml
- includes/rest/class-webfinger.php
It fixes #152 but I am not sure this changes anything, unless mastodon will also support it. I am curious.
Thanks @mediaformat for filing the issue on webfinger.net: https://github.com/webfinger/webfinger.net/issues/28
> Fix webfinger

- includes/rest/class-outbox.php
This add contents from all enabled post types into the outbox API output, instead of the previously hardcoded `"post"` type.
> Add Custom Post Type support to outbox API

- includes/functions.php
> Fix typo in get_remote_metadata_by_actor

- README.md
- readme.txt
> improve readme

- includes/class-health-check.php
This PR improves the documentation and fixes some typos in the Health Check class.
> Health Check: Fix documentation and typos.

- readme.txt
> Compatibility: mark plugin as compatible with WP 6.2.

- .github/PULL_REQUEST_TEMPLATE.md
This should help folks craft Pull Request descriptions that are as helpful as they can be.
* Not much to test here; check for typos.
> General: add PR template

- activitypub.php
- includes/collection/class-followers.php
- integration/class-wp-sweep.php
thanks @akirk
https://github.com/polylang/polylang/commit/b0db9db87ea4c765f85c4478454bc4b95ebf8917
Fixes sweeping of the Followers-Taxonomy and Terms
*
* Go to '..'
*
> prevent sweeping of followers taxonomies

- includes/collection/class-followers.php
Adds Inbox-Caching
* Cache Follower-Inbox-List
> Introduce Caching

- includes/activity/class-activity-object.php
- includes/activity/class-actor.php
- includes/activity/class-base-object.php
- includes/activity/class-person.php
- includes/class-migration.php
- includes/class-scheduler.php
- includes/collection/class-followers.php
- includes/functions.php
- includes/model/class-follower.php
- includes/rest/class-followers.php
- includes/table/class-followers.php
- templates/followers-list.php
- tests/test-class-activitypub-activity-dispatcher.php
- tests/test-class-activitypub-activity.php
- tests/test-class-activitypub-mention.php
- tests/test-class-db-activitypub-followers.php
For #344 we need some more informations from the Follower, so I introduced an Actor object. This allows us to transform the Follower into a valid Actor, that can be used in API representations.
And some open fixes from the last PR #347
/cc @mattwiebe 
*
* Go to '..'
*
> A Follower is now an ActivityPub Actor

- README.md
- includes/class-shortcodes.php
- includes/functions.php
- readme.txt
- tests/test-class-activitypub-shortcodes.php
Checks if item (WP_Post) is "public", a supported post type  and not password protected.
Fixes internal review
*
* Go to '..'
*
> Hardening the use of a shortcode

- activitypub.php
- includes/class-admin.php
- includes/class-health-check.php
- includes/functions.php
- includes/table/class-followers.php
- templates/admin-header.php
- templates/user-settings.php
This will allow us to get past the lint bots on dotcom
*
* Go to '..'
*
> Lint: now clean

- readme.txt
The changelog needed a little updating and reordering for 1.0
*
* Go to '..'
*
> 1.0 changelog

- includes/class-activity-dispatcher.php
- includes/class-migration.php
fix issue with where multiple migrations run at the same time
> fix issue with where multiple migrations run at the same time

- includes/model/class-follower.php
- tests/test-class-db-activitypub-followers.php
this does not fix the issue, but UI shows fine for the moment.
> workaround for special chars

- includes/model/class-post.php
for a better backwards compatibility
@akirk can you check the code with the friends plugin?
> re-add post model

- includes/rest/class-inbox.php
Let's get to the bottom of why many comments don't even make it as far as spam!
> Add inbox create/react actions

- includes/model/class-blog-user.php
- includes/model/class-user.php
also `get_at_url` needed an update for the Blog User, who would throw an error otherwise
> Add a `get_webfinger_identifier` method

- includes/model/class-user.php
We already have `User::get_resource` to do the same, I just didn't dig enough.
> Revert `User::get_webfinger_identifier`

- includes/transformer/class-post.php
- templates/welcome.php
One of these days I will learn to catch these sooner. 
Not today, though.
> Lint: fix issues

- includes/activity/class-activity.php
- includes/class-signature.php
- includes/model/class-application-user.php
- includes/model/class-blog-user.php
- includes/model/class-user.php
- includes/rest/class-inbox.php
- includes/rest/class-server.php
- tests/test-class-activitypub-rest-post-signature-verification.php
Fixes some signature issues and the functionality of the application user.
> Fix some signature and application user issues

- includes/activity/class-base-object.php
- includes/class-scheduler.php
- includes/collection/class-followers.php
- includes/functions.php
Fixes https://wordpress.org/support/topic/php-error-when-viewing-ap-followers-via-json/
* Better error handling when data is missing
> better handling when data is missing

- includes/functions.php
> fix `is_single_user`

- includes/class-signature.php
- includes/transformer/class-post.php
- templates/settings.php
- tests/test-class-activitypub-post.php
Fixes #463 and remote deletes (mentioned in #465 )
*
1. write a new post
2. wait for it to be published on the fediverse
3. delete the post
4. check if post is deleted on all remote platforms
> Fixes PHP warnings and remote delete

- includes/model/class-blog-user.php
compatibility improvements with Groups
* Add moderators endpoint as `attributedTo` property
> add moderators as attributed_to

- includes/class-admin.php
Fixes #470
* Add a check that validates that the blog-users name is not colliding with the login name of an Author (WordPres user).
* Go to '..'
*
> check if blog-user collides with a username

- includes/model/class-blog-user.php
- includes/transformer/class-post.php
Fixes #475
Fixes #452
Fixes #382
Fixes #454 
* Fixed various encoding and display issues.
> Fix various encoding issues

- includes/class-health-check.php
See https://github.com/Automattic/wordpress-activitypub/discussions/479
* Check author URLs only if authors are enabled
* Fall back to blog-user, to test WebFinger endpoint, if authors are disabled
* Go to '..'
*
> Fix the health check

- includes/functions.php
> do not show block for WP versions below 5.9

- .distignore
- CODE_OF_CONDUCT.md
- LICENSE
- SECURITY.md
Add:
* Security Policy (based on the Jetpack repo)
* Code of Conduct (based on Contributor Covenant)
> Add "Security Policy" and "Code of Conduct"

- activitypub.php
Fixes https://github.com/Automattic/wordpress-activitypub/issues/482#issuecomment-1755797534
thanks for reporting @sjn
> fix a race condition

- includes/functions.php
because of several issues
fix #514
Fixes #
*
* Go to '..'
*
> increase timeout

- includes/class-signature.php
- includes/collection/class-followers.php
- includes/functions.php
- includes/model/class-application-user.php
- includes/rest/class-inbox.php
- includes/rest/class-server.php
Fixes various errors
*
* Go to '..'
*
> Various improvements

- README.md
- activitypub.php
- includes/rest/class-following.php
- readme.txt
Fixes broken following endpoint
*
* Go to '..'
*
> fix following endpoint

- README.md
- activitypub.php
- includes/class-signature.php
- readme.txt
The API can return 410 errors and this can be misinterpreted
*
* Go to '..'
*
> improve error messages and codes

- includes/compat.php
- includes/rest/class-collection.php
- includes/rest/class-following.php
- includes/rest/class-nodeinfo.php
- includes/transformer/class-post.php
We have a bot on dotcom that's bugging us about various things related to PHP 8.1 compatibility. All of these shouldn't change anything functionally, but will make our merges less noisy, and possibly guard against some obscure fatals.
> PHP 8.1 compatibility

- includes/class-shortcodes.php
- readme.txt
Fixes #520
* Change the way how to get the author and the authorurl of a post. See #520 for details
* Go to '..'
*
> More reliable way to get author and autorurl

- includes/functions.php
- includes/rest/class-nodeinfo.php
- integration/class-nodeinfo.php
> Add monthly active users

- includes/functions.php
Fixes #521 
* Check if post type is supported by ActivityPub
> Check if the current post type supports ActivityPub.

- includes/handler/class-delete.php
Fixes #554
Rebases #561
* Schedules deleting all the comments of a deleted actor
* Go to '..'
*
> schedule delete comments of deleted actor

- activitypub.php
- build/follow-me/index.asset.php
- build/follow-me/view.asset.php
- build/followers/index.asset.php
- build/followers/view.asset.php
- includes/class-activitypub.php
- includes/class-admin.php
- includes/class-blocks.php
- includes/class-signature.php
- includes/collection/class-followers.php
- includes/collection/class-interactions.php
- includes/rest/class-followers.php
- includes/rest/class-inbox.php
- tests/class-activitypub-testcase-cache-http.php
- tests/test-class-activitypub-activity-dispatcher.php
- tests/test-class-activitypub-activity.php
- tests/test-class-activitypub-followers.php
- tests/test-class-activitypub-rest-post-signature-verification.php
> some phpcs fixes

- includes/collection/class-users.php
- includes/rest/class-webfinger.php
- integration/class-webfinger.php
- tests/test-class-activitypub-users-collection.php
Add support for URLs and some wildcards like for example:
* `http(s)://domain`
* `acct:@domain`
* `acct:_@domain`
* `acct:*@domain`
See: https://github.com/mastodon/mastodon/issues/22213
/cc @snarfed @manton 
*
> WebFinger: Add support for URLs

- activitypub.php
- includes/handler/class-create.php
- includes/handler/class-delete.php
- includes/handler/class-follow.php
- includes/handler/class-undo.php
- includes/handler/class-update.php
- includes/model/class-user.php
- includes/rest/class-inbox.php
There seem to be platforms that require a shared inbox, even if it is optional and does not make a lot of sense for a WordPress Blog.
> Shared Inbox

- includes/transformer/class-post.php
The filename with -scaled in it is used as the primary key in this case (for images wider than 2560px, by default). If a small version of one of these images, say `foo-500x500,jpg`, is embedded into a post, the correct primary URL to look up is `foo-scaled.jpg`. Sorry I didn't catch this before!
Fixes #
* Fix lookups to try the -scaled URL correctly.
* Upload an image wider than 2560 pixels.
* Insert this into a post (but don't make it the featured image).
* View the post via AP.
* Confirm that the image is now correctly attached.
> Fix classic editor image finding for large images

- includes/class-scheduler.php
- includes/transformer/class-comment.php
Fixes #649
/cc @janboddez @mediaformat
> fix comment update federation

- activitypub.php
- includes/model/class-follower.php
- integration/class-enable-mastodon-apps.php
see https://github.com/akirk/enable-mastodon-apps/pull/67
/cc @akirk
> implements a basic followers endpoint for the mastodon api

- includes/class-activitypub.php
- includes/class-admin.php
- includes/rest/class-outbox.php
- templates/settings.php
- tests/test-class-activitypub-shortcodes.php
* Remove `page` from default types (fix #665)
* Add description to settings (fix #673)
*
> Improve `post-type` support

- includes/functions.php
- templates/settings.php
* change description
* add default description for Attachments
see #673
What do you think @suramyatomar and @docpop ???
> improve the settings screen

- README.md
- activitypub.php
- includes/functions.php
- readme.txt
helps with #580
@timnolte & @snarfed what would you prefer? opt-in or opt-out?
> re-add vary header

- includes/class-debug.php
- includes/transformer/class-comment.php
> Apply `comment_text` filter to Activity

- includes/class-blocks.php
Fixes https://wordpress.org/support/topic/where-is-the-leading-in-the-sites-address/
> Add `@` prefix to Follow-Block

- includes/class-webfinger.php
See
* https://github.com/swicg/activitypub-webfinger/issues/3
* https://docs.joinmastodon.org/spec/webfinger/#example
> also support `application/ld+json` mime-type with AP profile

- activitypub.php
- includes/class-activity-dispatcher.php
- includes/class-activitypub.php
- includes/class-admin.php
- includes/class-migration.php
- includes/class-scheduler.php
- includes/collection/class-users.php
- includes/functions.php
- phpcs.xml
- tests/bootstrap.php
- tests/test-class-activitypub-followers.php
- tests/test-class-activitypub-user.php
* Use an ActivityPub capability to better enable/disable ActivityPub support
Fixes #259
*
* Go to '..'
*
> Improve User management

- includes/class-http.php
- includes/functions.php
- includes/rest/class-followers.php
- includes/rest/class-following.php
- includes/rest/class-inbox.php
- includes/rest/class-nodeinfo.php
- includes/rest/class-outbox.php
Show only `<major>.<minor>` and hide `<patch>` and beta infos
> Mask version number

- integration/class-enable-mastodon-apps.php
This adds a missing static keyword and don't bail out if the user id is 0 but data could otherwise be augmented.
> Enable Mastodon Apps Integration: Fix search

- includes/collection/class-users.php
- tests/test-class-activitypub-users-collection.php
> Fix blog-wide account when WordPress is in subdirectory

- includes/transformer/class-post.php
This should reduce the load of the fediverse crawlers after federating a post.
Thanks @tellyworth for the idea!
> Improve attachment handling

- integration/class-enable-mastodon-apps.php
This is now done in EMA itself: https://github.com/akirk/enable-mastodon-apps/pull/134
> EMA: Remove ensuring numeric ids

- includes/class-activitypub.php
Should fix #743
/cc @janboddez
> better conneg handling

- includes/class-admin.php
Fixes #791 
This should fix the issue when using a screen reader. Thanks for the report @talksina and your guidance!
> added screen-reader-text

- includes/class-migration.php
- tests/test-class-activitypub-followers.php
> Fix Fatal Error: wp_schedule_single_event third argument is being passed as a string

- includes/class-activitypub.php
- includes/model/class-user.php
> Fix extra fields

- includes/class-admin.php
Add line brakes for user bio see #828
> Add line brakes to user biography

- activitypub.php
- includes/transformer/class-post.php
- integration/class-seriously-simple-podcasting.php
- integration/load.php
This implements a Transformer that adds a podcasts audio file to the attachments.
> Refactor Media Handling a bit and add support for Seriously Simple Podcasting

- includes/class-activitypub.php
- templates/welcome.php
Maybe fixes https://wordpress.org/support/topic/bookmarklet-seems-to-do-nothing/
*
* Go to '..'
*
> Hide Bookmarklet if site does not support Blocks

- activitypub.php
- includes/class-hashtag.php
- includes/class-link.php
- includes/class-mention.php
- includes/class-shortcodes.php
- includes/collection/class-extra-fields.php
- includes/functions.php
- includes/transformer/class-post.php
- tests/test-class-activitypub-shortcodes.php
See #848 also #556
*
* Go to '..'
*
> Support "read more" for Activity-Summary

- includes/class-blocks.php
> Improve Accessibility for Reply-Context

- README.md
- readme.txt
Fixes #
* Added information about use behind an Apache reverse proxy discovered in case 879
> Added documentation for setup behind reverse proxy with Apache

- activitypub.php
- includes/class-cli.php
- includes/class-scheduler.php
> A CLI extention to help with manual updates, deletes and a self-destruct feature
