Automattic/wordpress-activitypub

includes/model/class-post.php

Add image alt text to the ActivityStreams attachment property in a format that Mastodon can read.

Federate image descriptions if present

---

includes/rest/class-nodeinfo.php

Give nodeinfo services the same indexing privileges as web crawlers based on the wordpress setting `blog_public` :
> Discourage search engines from indexing this site
If the option is enabled, the nodeinfo path returns a 404 error as per the [protocol](https://github.com/jhass/nodeinfo/blob/master/PROTOCOL.md)

Only return nodeinfo data if site is public

---

includes/model/class-post.php

In my own testing, I have found that the post timezone was skewed by its distance from GMT.
WordPress post object includes a timezone neutral `post_date_gmt`, using this allows peers to display the correct post date-time. 
#63

Fix timezone

---

readme.txt

What you can find on https://gnu.io/social doesn't even support ActivityPub.

Link to a GNU Social fork that is under active development

---

activitypub.php

Matches any string starting with '#' and consisting of any number and combination of [A-Za-z0-9_] that is directly followed by whitespace or punctuation. Groups everything after '#' for access in functions using this regex.
This potentially fixes #183 (incomplete links on hashtags containing special characters) by not matching these at all - although it seems as if strings containing Umlaute etc. actually can be used in hashtags (search for #ÖPNV, for example).

change regex matching potential hashtags

---

README.md
activitypub.php
readme.txt

next release fokus: https://github.com/pfefferle/wordpress-activitypub/pull/142

prepare 0.14.0

---

includes/functions.php
integration/class-friends-feed-parser-activitypub.php

Fixes #219 which exposes a bug where we try to use a WP_Error to create a transient key.

Don't access transient when receiving a WP_Error

---

activitypub.php
includes/class-admin.php
includes/model/class-post.php
templates/settings.php

Currently the plugin sends up to three images when publishing via ActivityPub.  This is probably more than Mastodon users, especially, are used to.  This is particularly true if you're only publishing an excerpt of the full article.  Alternatively, for very image-heavy posts, it might not be enough.  It should be configurable.

configuration item for number of images to attach

---

assets/css/activitypub-admin.css

Currently, if you save settings, the two notice boxes sit righ on top of each other like so:
Which is a little ugly, so give them some space by adding a top margin:

Give the notice boxes some margin so they have some space.

---

includes/model/class-post.php

The existing implementation crops at words and may return very short strings based upon filters, or very long strings based upon user inputted excerpts.
For example:
- Any user created excerpt isn't cropped at any length as it's just passed straight back.
- The excerpt length is filtered with `excerpt_length`, but that returns a number of words, not characters.
- User excerpts are not converted to plain text before being passed into the final filter which could cause unexpected outcomes.
This PR does the following:
- Treats manual and content based excerpts similarly, stripping tags, and making sure they are the correct length.
- Returns an excerpt based on character count, not word count.
- Does *not* use the `excerpt_length` filter.
- Tries to ensure that the excerpt is never more than …

Make the excerpt code actually crop the excerpt at 400 characters.

---

activitypub.php
includes/class-activitypub.php

This is for two reasons:
- No need to add the endpoint every time the plugin loads.
- The old code didn't flush the rewrite rules, making the endpoint non-functional until something did (like the user saving the permalink settings)

Move the activitypub endpoint rule to the main rewrite addition function

---

includes/class-hashtag.php

If your post has HTML that contains something that resembles a hashtag, the ActivityPub plugin currently breaks that tag by replacing new HTML tags into the other tag.
Specifically, this HTML:
```
<span style="color: #ccc">Only friends</span>
```
will be transformed to this:
```
<span style="color: <a rel="tag" class="u-tag u-category" href="https://alex.kirk.at/tag/ccc/">#ccc</a>;&#8221;>Only friends</span>
```
which visually appears like this:
This PR adds protection of the tag before the replacing operation happens and then replaces them back in, resulting in unmodified tags inside HTML:

Hashtags: Protect HTML tags from being broken

---

includes/model/class-post.php

In dbaddd91890f4926ce3f8055e1c35947119dbd2f accessing the properties of the inner WP_Post was broken. I discovered this while rebasing #213 which has tests for this.

Fix accessing post properties

---

includes/class-hashtag.php
includes/class-mention.php
tests/test-class-activitypub-hashtag.php
tests/test-class-activitypub-mention.php

We also need to prevent the code between HTML elements in some cases, for example inside `<code>` or `<pre>`. This adds some more unit tests as well.
```
<pre>
Please don't mention @username@example.org
here.
</pre>
```
should not become
```
<pre>
Please don't mention <a rel="mention" class="u-url mention" href="https://example.org/users/username">@<span>username</span></a>
here.
</pre>
```
See https://wordpress.org/support/topic/block-shows-raw-html-on-frontend/

Protect HTML between certain tags

---

includes/class-webfinger.php

This should avoid warnings like this one:
```
PHP Warning:  Attempt to read property "user_login" on bool in /var/www/html/wp-content/plugins/activitypub/includes/class-webfinger.php on line 27
```

Webfinger info: avoid PHP warning when user isn't defined

---

includes/class-activitypub.php

I saw that many people have problems (including with WordPress caching plugins) but also with Cloudflare, that JSON is being delivered instead of HTML. This is because we're not announcing that multiple versions exist depending on an incoming `Accept:` header. This can be fixed through a `Vary` HTTP header, see https://www.fastly.com/blog/best-practices-using-vary-header

Fix Edge Caching Problems

---

activitypub.php
includes/class-admin.php
includes/functions.php
templates/author-json.php
templates/user-settings.php

Address issue #165, a feature request for a user bio specific to the fediverse, separate from the WP standard user description field.
The PR provides the following
- A const for the user meta key for storing/retrieving the AP bio
- Profile fields and save handling for the AP bio on the user edit screen; as implemented here the form field only displays when a user is editing their own profile; if the ability to see and/or edit another user's AP bio is desired, e.g. an Administrator editing a Contributor's AP bio, I can add that to this PR; it's two additional action hooks and some extra capability checks at most
- Template helper to display the AP specific bio first, if set, or defer to the default; an empty string is returned if both are unset
- Updates the author-json.php template to use …

Add ActivityPub specific user description

---

includes/class-admin.php

Follow-up from #304
Since we do not use a constant anywhere else just yet, let's keep using a string in the settings page.

Profile settings: use string to fetch user description instead of constant

---

includes/class-migration.php

I think this should fix the problem of [$actor](https://github.com/Automattic/wordpress-activitypub/blob/master/includes/class-migration.php#L63) being undefined.
Untested.

fix migrate_from_0_17() error

---

includes/functions.php
readme.txt

This conditional could be used within the plugin, but also by third-party plugins, to detect whether a request is an ActivityPub request, without having to manually check for query vars and headers every time.
This is better tested with a code snippet, just like a third-party plugin would use on their end. Something like this:
```php
add_action(
'wp',
function () {
if ( function_exists( '\Activitypub\is_activitypub_request' ) ) {
error_log( 'the function exists' );
if ( \Activitypub\is_activitypub_request() ) {
error_log( 'This is an ActivityPub request' );
}
}
}
);
```
Then make requests and see the output of the function:
* Single posts
* Single posts with a custom `Accept: application/activity+json` header.
* Archive pages.

Compat: introduce a conditional to detect ActivityPub requests

---

activitypub.php
includes/class-activitypub.php
includes/functions.php
includes/model/class-activity.php
includes/model/class-post.php
includes/rest/class-followers.php
includes/rest/class-following.php
includes/rest/class-inbox.php
includes/rest/class-nodeinfo.php
includes/rest/class-ostatus.php
includes/rest/class-outbox.php
includes/rest/class-webfinger.php
templates/author-json.php
templates/blog-json.php
tests/test-class-activitypub-activity.php

As discussed elsewhere, the REST API will need to land within a `wpcom/*` namespace to work with our very particular requirements on wordpress.com. This change should allow it to be configurable by us or anyone who would want to use a different namespace in their own environment.
* Introduce a `ACTIVITYPUB_REST_NAMESPACE` constant that can be overridden from the default `activitypub/1.0` namespace.
I don't know how, yet. :)

Allow setting the REST namespace with `ACTIVITYPUB_REST_NAMESPACE`

---

activitypub.php
composer.json
includes/class-mention.php
includes/class-shortcodes.php
includes/rest/class-inbox.php
includes/transformer/class-post.php
phpcs.xml

Probably worth investigating how Jetpack runs their phpcs setup as they're merging frequently into dotcom but this works reliably up and until latest PHP versions
```
composer install
composer run lint
```

Lint: Try dotcom's set of sniffs

---

includes/transformer/class-post.php
readme.txt

This PR should just avoid a PHP notice when using PHP 8.2:
```
PHP Deprecated:  Creation of dynamic property Activitypub\Transformer\Post::$attachments is deprecated in /var/www/html/wp-content/plugins/activitypub/includes/transformer/class-post.php on line 249
```
Not much to test here; if you have a local installation of WordPress using PHP 8.2, you should no longer see the deprecation notice when trying to access a post in an ActivityPub request.

Compat: avoid PHP notices when using PHP 8.2

---

README.md
readme.txt

WordPress 6.3 will be released in the next few weeks. Let's indicate that the plugin is compatible with this new version.
Not much to test here. You can try running the plugin on a site running WordPress and [the WordPres Beta tester plugin](https://wordpress.org/plugins/wordpress-beta-tester/) set to Bleeding edge. Everything should still work.

General: update tested WP version for upcoming WordPress 6.3.

---

activitypub.php

Our notifications code on dotcom effectively called `class_exists( 'activitypub_followed_note' )` and caused a fatal error because it was trying to load `includes/class-activitypub-followed-note.php`
This is because the pre-existing code converts the checked class to lowercase before checking, whereas it should first ensure 1) we're using the capitalized version, and 2) we have a backslash to indicate actual namespaced code.

Autoloader: more precise matching

---

README.md
activitypub.php
readme.txt

Fixes #375
Let's try to load the plugin later in the WP lifecycle to avoid the Fatals happening in #375.
Related discussion: p1690454109597069-slack-C04TJ8P900J
* Is CI happy?
* Can you use the plugin on a multisite install with no errors?
* Can you visit wp-admin, frontend, and activitypub requests without any issues?

General: load plugin later.

---

includes/class-migration.php

This should fix the issue on .com that saves the subdomain.wordpress.com domain to the options table before custom domain is set.
/cc @mattwiebe

fix domain change issue on .com

---

includes/class-webfinger.php
includes/rest/class-users.php

Added in favour of #356 
The API works like: `https://example.org/wp-json/activitypub/1.0/users/1/remote-follow?resource=pfefferle@mastodon.social` and returns `{"url":"https:\/\/mastodon.social\/authorize_interaction?uri=test@localhost"}`
* Added functions to get Remote-Follow endpoint from Remote-Server
* Added API endpoint to query that endpoint

remote-follow endpoint

---

includes/rest/class-inbox.php

Akismet tries to add a nonce to harden spam submissions. Since these comments aren't submitted through the comment box, we should disable that.

Disable the akismet nonce when processing our comments

---

includes/model/class-blog-user.php

The Blog User was not returning the `site_icon` option. Now it is.

Add site logo support to blog user

---

README.md
package.json
readme.txt
templates/admin-header.php
templates/blog-user-followers-list.php
templates/settings.php
templates/user-followers-list.php
templates/user-settings.php
templates/welcome.php

The readme needed a lot of attention since we now have a blog-wide user since #342!
Otherwise, I have consolidated naming things as **Blog profile** and **Author profile** for user-facing documentation. We call them `Blog_User` and `User` in code but this seems to be better user-facing language.
I've also made some edits to make things more idiosyncratically English, such as removing hyphens and capitalizations that are typical *auf Deutsch*.
<table width="100%">
<thead>
<th width="100px">Screen</th>
<th>After</th>
<th>Before</th>
</thead>
<tbody>
<tr>
<td>
Welcome 
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
Settings 
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
Blog Followers 
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
Author Followers 
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
User …

Words: copy and language consistency/improvements everywhere

---

includes/class-signature.php
includes/model/class-application-user.php
includes/model/class-blog-user.php
includes/model/class-user.php
tests/test-class-activitypub-rest-post-signature-verification.php
tests/test-class-activitypub-signature.php

A problem we've run into for WP Multisite is that there is theoretical key leakage for a given user who is a member of more than one network blog.
Imagine `example.com` as a WP Multisite install. Two users, `foo` (ID 1) and `bar` (ID 2), have a shared site called `foobar.example.com`, while `foo` has a solo site, `foo.example.com`. Since usermeta is shared across the whole network, `bar` could be sneaky and retrieve `foo`'s private key from their shared site. `bar` could then use that private key to sign private messages on the fediverse _as though it was coming from `@foo@foo.example.com`_ rather than `foo@foobar.example.com`, or any other site on that network on which `foo` is a member.
What this patch does is to migrate keypair storage to be based on blog options instead, which will …

Store keypairs as options keyed to user IDs.

---

includes/class-webfinger.php

Fixes #422
* Authors who use a subdirectory have to redirect `/.well-known` - this allows the health check to pass.
* Create a blog at example.com/blog/
* Install the plugin
* Configure .htaccess as described to redirect `/.well-known/` to `/blog/.well-known/`
* Run the WordPress health check
* Note that it fails.
* Apply this patch.
* Success!

Follow redirects in class-webfinger.php

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/workflows/gardening.yml

The Repo Gardening action is a tool that one can use to automate some of the tasks that you can perform to monitor activity in your repository.
https://github.com/marketplace/actions/repository-gardening
It includes different tasks, that can be enabled based on your needs.
This PR gets us started with the action by enabling a few tasks.
- This action relies on a few secrets that have already been added to this repo.
- Of note, `gatherSupportReferences` and `replyToCustomersReminder` aren't too useful right now, but will become useful once the plugin is released on WordPress.com and once we start receiving feedback from WordPress.com site owners.
- The `flagOss` task will point to #fediverse for now. This can be updated later on.
- I've added mapping for our 2 block directories, but that …

Repository maintenance: add GitHub Repo Gardening action and issue templates

---

README.md
includes/transformer/class-post.php
readme.txt

Follow-up to #309
It should be '_post', not twice '_pre'.
Not much to test here, that was just a stupid typo of mine...

Post images: fix a typo in the hook name

---

README.md
readme.txt

Fixes #419 
* Blogs in subdirectories didn't work with the previous `.htaccess` rule
* Create a blog in a subdirectory - for example `example.com/blog/`
* Try to use the original `.htaccess` file
* Note that visiting `https://example.com/.well-known/webfinger` gets redirected to `https://blog///.well-knownwebfinger`
* Try this new, improved, organic, fat free, low-sugar `.htaccess` file
* Rejoice as you are redirected correctly.

Fix .htaccess issue with subdomain

---

includes/class-http.php
includes/class-signature.php
includes/collection/class-followers.php
includes/functions.php
includes/model/class-follower.php

It seems that version 1.0.0 produces a higher amount of http 500 errors. It seems that this is the case if you return an WP_Error without defining the status code.
* Add status code to most of the WP_Error messages
* Go to '..'
*

WP_Error: add status message if it might be returned by API

---

README.md
includes/class-signature.php
readme.txt

fix #421
* The current code ignores the 'path' when generating the signature string. This PR should fix the issue.
* Install WordPress in a sub directory
* Install ActivityPub
* Try to follow your blog from Mastodon or a similar platform

add path to route

---

includes/class-hashtag.php
includes/class-mention.php
tests/test-class-activitypub-hashtag.php
tests/test-class-activitypub-mention.php

This provides a more solid approach for ensuring that mentions and hashtags are not applied within certain tags.
* Use `wp_html_split()` and a tag stack to protect tags
This doesn't change functionality.
* Run the unit tests to ensure they still pass.

Hashtags, Mentions: Use a tag stack instead of regex for protecting tags

---

includes/transformer/class-post.php

This will prevent the issue of attaching images that don't were uploaded to the post but not used in the post
The post needs to be using blocks to get the introspection required.
Fixes #447
Use the blocks parser to fetch actually-used images from the post.
With this PR active, upload two images to a post. Only use one of them. Before this, both images would be attached to the Activity as attachments. After this, only the image that gets inserted in the post will be used.
This has the added benefit of being able to use images in a post that weren't uploaded against it, eg reusing previously-used images.

Activity: try to parse image IDs using blocks

---

includes/transformer/class-post.php

Hashtags to be displayed separately when they are the last line of a post in Mastodon 4.2+
Fixes #432
* Moves `[ap_hashtags]` last in post in Content

Move [ap_hashtags] last in post in Content

---

includes/class-health-check.php
includes/class-scheduler.php

Fixes high load on page visits for users, that use the default setup of WP_Cron.
* WP_Cron on page visit: 5 checks
* Systems Cron: 50 checks
Context: https://wordpress.org/support/topic/upgraded-to-1-0-user-account-can-no-longer-be-followed-replies-broken/
* Reduce default to 5 checks and increase up to 50 if `DISABLE_WP_CRON` is true.

reduce number of checks when system cron is not used

---

activitypub.php
includes/class-activitypub.php

We are running into problems on dotcom, where we need to use a different rewrites setup than the plugin for esoteric reasons I won't get into here. This may not be the best way, but it's just the blunt force tool we need right now.
Fixes #
* If you set `ACTIVITYPUB_DISABLE_REWRITES` to `true`, the plugin will not add rewrites.
* Go to '..'
*

Add a `ACTIVITYPUB_DISABLE_REWRITES` constant

---

includes/transformer/class-post.php

do not overwrite $image_ids to include post thumbnail also for block-parser.
Fixes https://wordpress.org/support/topic/setting-number-of-images-sends-one-less-than-intended/
* The current version replaces the `$image_ids`, so the featured image will be replaced and the number of images does not match any more.

Fix: missing featured image when using blocks

---

includes/class-mention.php
integration/class-webfinger.php

Fixes `[12-Oct-2023 10:15:38 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method Activitypub\Integration\Webfinger::get_profile() in /.../wp-content/plugins/activitypub/integration/class-webfinger.php:55`
thanks for reporting @akirk

fix function call

---

activitypub.php
includes/functions.php

To filter the `\get_option( 'blog_public', 1 )` output, this is important for the use in the `public-api` context of wp.com

add filter to check if blog is public

---

includes/help.php

* Just fixing a typo "lenght" -> "length"
* Go to the help page.
* Make sure it says `[ap_excerpt length="400"]`

Fix typo "lenght" in help page

---

activitypub.php
includes/class-shortcodes.php
includes/transformer/class-post.php
tests/test-class-activitypub-shortcodes.php

I was poking around with post rendering and I thought it would be better to make sure that our shortcodes are never available outside of our own rendering context.
And of course I pushed these changes to `master` accidentally. 🤦 
I'll have to see if this breaks tests.

Shortcodes: only register when needed

---

includes/transformer/class-post.php
readme.txt
templates/settings.php

* support attaching both audio and video uploads!
Note that audio and video are only supported in the block editor. 
Audio and video files are also currently constrained by our max_images number. That may lead to confusion?
* upload a video and/or audio file to a post, they should show up in the activitypub version of the post. You can append `/activitypub/` to any given post URL and inspect the `attachment` value.

Attachments: add support for audio 🔈 and video 📼

---

includes/class-mention.php

At scale, we begin to see some odd use-cases. There is one particular individual with a 2MB post that is failing repeatedly (our jobs system continually retries after fatal errors) while trying to convert mentions into links due to execution timeouts.
* add a 1MB limit to attempting to link
I don't really suggest trying to federate a post this large! 
* Go to '..'
*

Mentions: 1MB limit for attempting to link mentions, otherwise bail

---

includes/class-hashtag.php
readme.txt

Following on from #540 , this will also bail early when attempting to link hashtags, to prevent fatal error timeouts that will fail to federate the published post.
* add a 1MB limit to attempting to link hashtags
* Go to '..'
*

Hashtags: 1MB limit for attempting to link

---

includes/transformer/class-post.php

for example  "de" instead of "de_DE"
Fixes #548 and should also help with #151 #19 
* The change now supports CLDR and ISO-639-1 codes.
@mattwiebe this is important, because it breaks the compatibility with some platforms on WordPress.com

fix: support also ISO-639-1 codes

---

includes/transformer/class-post.php

Our dedupe logic ran too late, after already scoping to max_media, which would sometimes result in fewer attachments than warranted by `max_media`. 
This would happen especially in the case of a Featured Image also appearing in the `post_content`.
Fixes #560 
* dedupe attachments before cutting to max_media
Make a post with more images than your max media. Add a feature image and also add it as a standalone image in post_content. The ActivityPub representation will have one fewer attachment than it should have without this patch, the correct number with it.
Eg, with a local post and `max_images=3`:
```
curl -H 'Accept: application/activity+json' http://wp.test/2023/10/301/ | jq .attachment
[
{
"type": "Image",
"url": "http://wp.test/wp-content/uploads/2023/08/avatar-2017-large-upsidedown.j …
```

Attachments: dedupe earlier to prevent incorrect max_media

---

includes/help.php
templates/settings.php

Fixes #577 
* Clarifies what [ap_excerpt] does exactly in the relevant places (main Settings page and help.php)
* No change in behaviour, just a change to clarify documentation. It should be clear to users that this respects `the_excerpt` if available, and otherwise truncates the post at `length`.
* Go to ActivityPub > Settings
* The relevant descriptions should be updated to be more clear and less ambiguous about what it means to choose [ap_excerpt]. It will be clear to users that it respects `the_excerpt` if available, and otherwise truncates the post at `length`.

Clarifying what [ap_excerpt] does

---

includes/collection/class-followers.php

Fixes #587 
Disable pagination on the query in `Followers::get_inboxes()` that looks up follower IDs. This causes it to return all followers, rather than a paged list of ten of them. This means that we end up delivering our post to all followers, and not to the instances belonging to a subset of ten of them.
* You need an instance with more than ten followers from different instances for a profile (user or blog) to demonstrate the issue here.
* Log outgoing posts in some way.
* Prior to the fix, you'll see that when a post goes out, at most ten instances (and often fewer, if you have more than one follower per instance) actually get sent the message.
* With this fix, all should get them.
* Alternatively, use something like `wp shell` from `wp-cli` to run the queries in before and after …

Fix sending posts to at most ten instances

---

includes/class-shortcodes.php
tests/test-class-activitypub-shortcodes.php

Fixes #558 
* `excerpt_more` might already be customized by themes. Using `activitypub_excerpt_more` to allow more specific control.
* Use a theme with custom `excerpt_more` filter, for example twentyfiteen.
* The `[ap_excerpt]` shortcode should not be affected by the `excerpt_more` filter.

replace `excerpt_more` with custom filter `activitypub_excerpt_more`  for better consistency

---

includes/rest/class-nodeinfo.php

This is a very tiny pull request that adds some metadata fields for the nodeinfo representation.
Both `nodeName` and `nodeDescription` are already widely adopted.
More info to the current status can be found here: https://codeberg.org/thefederationinfo/nodeinfo_metadata_survey
`nodeIcon` is not used yet, I proposed it myself as it could yield to use cases later. Most WordPress sides are highly customized and styled. They have a favicon that people already identify the site with. Maybe other software will make use of this in the feature, like Mobilizon when following the application actor of a WordPress site (see https://framagit.org/framasoft/mobilizon/-/merge_requests/1513).

Add nodeinfo metadata

---

includes/class-admin.php
includes/class-blocks.php
tests/test-class-admin.php

Fixes #609
This displays an admin notice if the permalink structure is plain.  This is because the plugin cannot function correctly with such a permalink structure, it prevents webfinger from working.
Tests have been added.
I am not sure about the implementation.  The admin notice is pretty bold.  Perhaps a more subtle notice makes sense?
The implementation is designed to allow for many warnings.  At the moment there is only this one.  I imagine in future other issues could be detected here.  For example there is currently conflicts with the One User Avatar and Comment Like Dislike plugins.  This would be an appropriate mechanism to flag those issues.
Testing:
* Create a fresh wordpress instance, but do not set a permalink structure.
* Install the activitypub plugin
* Observe …

show admin notice when permalink structure is plain

---

includes/transformer/class-post.php

Fixes #612 
Fixes #553 
I note that work on this issue hasn't been officially prioritised due to the deprecation of the classic editor, but we're still using it so here we are.
* If we're using the classic editor on a new enough version of WordPress to have the `WP_HTML_Tag_Processor` available, use this to pull all `<img>` tags out of the post. Grab their sources, and if they point at our uploads directory, use them in the federated representation of the post.
* There's a slightly hairy bit of code to handle different-sized versions of images - I played around with a few options here including trying to parse `srcset` but decided the simplest and most reliable option is to attempt to look the URL up directly, and _iff_ that fails use a regex to drop suffixes of the type `-500x500` or …

Add improved classic editor image detection

---

includes/transformer/class-attachment.php
includes/transformer/class-base.php
includes/transformer/class-comment.php
includes/transformer/class-post.php

I tried to improve the readability and the efficiency of certain custom transformers via:
- Renaming the property 'object' to 'wp_object' of the _Transformer_ classes  to indicate that its the source
- Adding an optional property 'activitypub_object' which may make already transformed parts available to other "getter" functions.
- Enhancing some PHP-Docs

Improve the property names of the transformer classes

---

includes/collection/class-interactions.php
includes/handler/class-update.php

Fixes some of the things found in #633
* So, `wp_update_comment()` doesn't actual return a comment ID.
* So I made it so that `Interactions::update_comment()` takes this into account and returns the `$commentdata` array, but only when the update was successful.
* If the update somehow failed, `Interactions::update_comment()` either returns `false` or `'invalid'` (just like before) or whatever is returned by `wp_update_comment()` (which can be an error, or `0`, or even `false`). Actually, in this case, the function behaves just like it did before.
* Subsequently, in the "update handler," I replaced `\get_comment( $state )` with something that I think makes a bit more sense (as mentioned, `$state` isn't actually a comment ID).
The way I tested this, is I created a callback in a separate …

Address some of things found in #633

---

integration/class-enable-mastodon-apps.php
tests/bootstrap.php
tests/test-class-enable-mastodon-apps.php

This moves functionality from the Enable Mastodon Apps into ActivityPub. It allows retrieving the account of someone via ActivityPub with an API endpoint like `/api/v1/accounts/alex@kirk.at/`
The unit test currently needs network access, we should add the ability to mock the response.

Enable Mastodon Apps: Implement the account endpoint for an external account

---

integration/class-enable-mastodon-apps.php
tests/test-class-activitypub-followers.php
tests/test-class-enable-mastodon-apps.php

For the Enable Mastodon Apps, when there is an request for an internal account, let's add the right followers_count.
This PR also adds HTTP mocking for the `test_api_account_external` test.

Enable Mastodon Apps: Add followers_count to internal accounts

---

includes/class-scheduler.php

Adds a `activitypub_update_followers_number` filter. May be silly, but for sites that _do not_ have `DISABLE_WP_CRON` set to true _yet do_ regularly trigger `wp-cron.php` via an actual cron job, the number of followers that are updated will _currently_ never be more than 5 at a time.
Having this number filterable allows site owners to set a number that may be more approiate for their install, or they can---in their callback---employ a different kind of check to see whether PHP is run directly, like `if ( 'cli' === php_sapi_name() )`.
May not be _that_ relevant if the server can act on follower updates, but I thought it wouldn't hurt either.
* Add a filter to allow devs to change the max number of followers that can be updated at once.
* N/A

Add `activitypub_update_followers_number` filter

---

includes/activity/class-activity.php

The `call_user_func` version seem to not work properly (returns `null` in this case https://github.com/Automattic/wordpress-activitypub/blob/master/includes/handler/class-follow.php#L98) in this case and this seems to break the follow flow.
/cc @Menrath

fix ActivityPub `@context`

---

includes/class-scheduler.php

Fixes an "undefined variable `$type`" warning.
* Replace `if ( ! $type )` (which throws a warning since I think PHP 8) with `if ( empty( $type ) )`
* I got this when deleting and restoring comments
* Maybe when the old status was `trash` and the new one `pending` or whatever it's called
* Either way, there are scenarios where `$type` does not get initialized, ever

Fix "Undefined variable $type in includes/class-scheduler.php on line 191"

---

README.md
includes/transformer/class-comment.php
readme.txt

Add all repliers as Mentions so that they receive notifications.
See: https://wordpress.org/support/topic/ux-deviation-from-expected-behaviour-in-2-0/

Add all repliers as Mentions

---

includes/class-activity-dispatcher.php
includes/class-admin.php
includes/class-scheduler.php

The current version works around all core verification processes to prevent duplicate schedules, because of the use of the `WP_Post` and `WP_Comment` object.
> Note that scheduling an event to occur within 10 minutes of an existing event with the same action hook will be ignored unless you pass unique $args values for each scheduled event.
>
> https://developer.wordpress.org/reference/functions/wp_schedule_single_event/
Because the objects are never the same, because of the content change and different update date-times, this check will never be valid, so this PR changes the code to use the ID instead of the object.
It also uses a more strict `wp_next_scheduled` check, to not only prevent a duplicate within 10 mins!
/cc janboddez

Prevent scheduler overload

---

includes/class-admin.php

The initial error message does highlight the problem, but provides no guidance how to fix it.  This expanded version provides some hints what to do next.
Fixes #664
* Expand error message with directions to the appropriate options page, and a hint as to what to select.
* Install fresh Wordpress
* Do NOT set a permalink structure
* Install Activitypub plugin
* Load WP console
* There will be a red warning message at the top, where the wording can be verified

Clarify how to set correct permalink structure (#664)

---

includes/class-comment.php

* Change comment reply link from "Reply" to "Reply with federation"
* Also adds a `title` attribute that currently says "is comment was received from the fediverse and your reply will be sent to the original author"
Try this on a post that has received a reply from the fediverse. The reply link, for a logged-in user who will be able to federate, will be changed like the screenshot above
* Go to '..'
*

Federated replies: improved UX for "your reply will federate"

---

includes/activity/class-actor.php

Fixes that the get_type function is not called for extended classes, when the property is already set.
There would have been two straight-forward solutions:
1. the proposed one
2. set`protected $type = '...'` in all extended classes of `Actor` and remove the `get_type` functions. 
I guess a test-case for this might be of good use. I will gladly add one if agreed.

Fix: ActivityPub type property does not set correctly on actor classes

---

includes/class-comment.php
includes/transformer/class-comment.php

Fixes #711 
Federate as the Blog User on `is_single_user` sites.
1. Add `define( 'ACTIVITYPUB_SINGLE_USER_MODE', true );` to your `wp-config.php`
2. Reply to a federated post from a Mastodon (or similar) service.
3. When logged in with a user with the `activitypub` capability, you should be able to reply to the post and have it federate - you should receive a notification on the service you used to make the comment in step 2.

Comment reply federation: support `is_single_user` sites

---

includes/rest/class-outbox.php

The outbox for the blog and the application user is currently empty, even if there are posts of a post type that have ActivityPub support enabled and the blog user is activated.

fix outbox collection for blog and application user

---

includes/class-signature.php
includes/collection/class-interactions.php
includes/collection/class-users.php
includes/handler/class-undo.php

See
* https://socialhub.activitypub.rocks/t/filtering-contents-from-the-fediverse-report/4061/25?u=pfefferle
* https://mastodon.social/@laurenshof@indieweb.social/112315027237003058
* Discourse uses Actor Objects instead of URIs
* Discourse adds the `expires` and `created` header only to the the signature header.
See headers
```
Array
(
[signature] => Array
(
[0] => keyId="https://socialhub.activitypub.rocks/ap/actor/...#main-key",algorithm="hs2019",headers="host date digest (request-target) (created) (expires)",signature="...",created="1713868503",expires="1713872103"
)
[content_type] => Array
(
[0] => application/ld+json; profile="https://www.w3.org/ns/activitystreams"
)
[digest] => Array
(
[0] => SHA-256=...
)
[date] => Array
(
[0] => Tue, 23 Apr 2024 10:35:03 GMT
)
[content_length] => …
```

Some fixes to be compatible with discourse

---

includes/transformer/class-post.php

Remote servers are expected to [sanitize content](https://www.w3.org/wiki/ActivityPub/Primer/HTML). 
In the case of `iframe` elements Mastodon and others simply drop them.
This PR pre-sanitizes the content, ensuring iframes display as links for remote servers.
Fixes #359 
* This uses the core/embed block filter to revert the iframe markup into a simple link block.
* Make a post inserting a youtube link (or from any of the [whitelisted providers](https://developer.wordpress.org/reference/classes/wp_oembed/__construct/) ), 
* The post content should display normally on site, showing the embedded iframe content
* The ActivityPub representation of the post should show the original link inside a paragraph

Adds a core/embed block filter to transform iframes to links 

---

includes/class-handler.php
includes/class-http.php
includes/handler/class-announce.php

Basic Announce support

---

includes/functions.php
includes/transformer/class-comment.php
tests/test-class-activitypub-comment.php

based in the `get_post_ancestors` method!
I have to test that a bit more, but I tried to adapt the `get_post_ancestors` to not have to use a limit!
What do you think @mattwiebe

Add generic get_comment_ancestors function

---

integration/class-enable-mastodon-apps.php

When clicking on a remote status, this will fetch the replies to this status via ActivityPub and return them in the context API call.

Enable Mastodon Apps Integration: Add remote context

---

integration/class-enable-mastodon-apps.php

When searching for a URL in a Mastodon App, this will now return the status.
Contains other fixes:
- Don't rely on some properties that misskey (or its fork iceshrimp) don't provide: status URLs (use the id), attachment sizes (don't calculate the meta), no blurhash (don't try to set it), accounts don't have a published date.

Enable Mastodon Apps: allow searching for URLS

---

includes/functions.php

After deploying #740 on dotcom, I noticed some infinite loop errors. This PR tightens up our comparisons and should prevent them. It fixes a case against production data.
* Tighter logic in `get_comment_ancestors` that ensures our comparisons will work properly and prevent infinite loops.
I'm unsure how to replicate the error, my brain says it should have been ok but it definitely wasn't. It would get stuck iterating over the immediate comment ancestor, in a comment 4 levels deep.

Prevent infinite loops in `get_comment_ancestors`

---

integration/class-enable-mastodon-apps.php

Before, we'd just fetch any statuses. Now this supports paging and distinguishes between replies and non-replies.

Enable Mastodon Apps: Add support for fetching external statuses without replies

---

includes/collection/class-users.php

Always fall back to `get_by_username`, even if `get_by_id` and `get_by_resource` fail.
This would allow us to also handle WebFinger resources without `acct:` scheme and still fall back to emails as user-names.

Always fall back to `get_by_username`

---

integration/class-jetpack.php

Follows on from #761
Sending notifications directly to wpcom didn't work as well, we can instead react on the server when the `ap_follower` post is received via Jetpack Sync. This ensures that the required metadata is sent.
With this patch running, on a site that's Jetpack-connected, try to receive a new follower. It should get Synced to wpcom and we should see the required metatdata on that side.
Requires D148889-code on wpcom server side to work. See full details there for testing, where it's working!

Use Sync for Jetpack notifications

---

integration/class-enable-mastodon-apps.php

Sometimes the `$user_id` might be the WebFinger handle. With this PR the plugin tries to resolve these cases internally first, before trying to look them up remotely.

Try to lookup local users first

---

includes/collection/class-users.php

We have some extra protections on dotcom for counting users in User queries, since we have a lot of users. Since we don't the total count anyway, we can make our query more efficient for everyone by skipping it :)
* Add `count_total => false` to our `WP_User_Query` instances

More efficient `WP_User_Query` with `count_total=false`

---

includes/class-comment.php

A really silly one, but I ran into it. :-)
`Comment::object_id_to_comment` returns either a `WP_Comment` (not an `int`, as I found out the hard way), or `false` (in which case I thought it's okay to make this explicit, although `boolean` isn't wrong)!
* Fix PHPDoc `@return` type

Update object_id_to_comment's PHPDoc

---

package.json

It turns out that v28 is only compatible with WP 6.6 and up. So we'll have to hold off for a while.
Previously reported in https://github.com/WordPress/gutenberg/issues/62202
Everything seems to build properly again after this. Just run `npm install` again.

Revert to @wordpress/scripts@27

---

activitypub.php
includes/class-admin.php
templates/settings.php

Fix #796
To be backwards compatible it is opt-out, but we can change it to opt-in if this is requested.

Add setting to enable/disable the `fediverse:creator` OGP tag

---

assets/css/activitypub-admin.css
assets/js/activitypub-header-image.js
includes/class-activitypub.php
includes/class-admin.php
includes/model/class-blog.php
includes/model/class-user.php
templates/admin-header.php
templates/blog-user-followers-list.php
templates/blog-user-settings.php
templates/settings.php
templates/user-settings.php
templates/welcome.php

Add "Header Image" support based on WordPress Site-Icon JS
Implements: #505 #768
Related: #584
See Blog-Settings:
See Author-Settings:

Add "Header Image" support

---

includes/transformer/class-post.php

Even after https://github.com/Automattic/wordpress-activitypub/commit/12cb73bcd678f3d2bde3c92f46a7dcb500e6e4f7 we are seeing fatal errors when saving drafts. 
This is also exposing an unintended problem with sending `Update` Activities for new drafts introduced in #780. I think we should only be sending those for previously-published posts?
* Include `wp-admin/includes/post.php` when needed
* Go to '..'
*

Fix undefined `get_sample_permalink`

---

includes/class-scheduler.php

In #780 we started sending `Update` Activities for drafts. But we should only be sending those if the post was previously published. The previous logic would always send for all draft status updates, which is probably spamming a bunch of instances with an update for a post that never existed.
* Fix `Update` logic to only send for posts transitioning from `publish` to `draft`
* Go to '..'
*

Only send `Update` for previously-published posts

---

includes/class-activitypub.php
includes/functions.php

Added menu_order to ap_extrafield so that user can decide in with order the Extra filds will be displayed.
* Add Support to Posttype for PAge attributes
* Add sorting to fields query
* Add a sorting on fields creation for user the first time
* Go to Users Profile and see the Extra fields in a sorted order
* On editing an Extra field have the option to change the order 
* In quick edit of the Extra fields have the option to change the order

Add ordering for Extra fields

---

activitypub.php
includes/class-activitypub.php
includes/class-admin.php
includes/class-scheduler.php
includes/collection/class-extra-fields.php
includes/functions.php
includes/model/class-blog.php
includes/model/class-user.php
templates/blog-settings.php
templates/user-settings.php

Following the pattern of User extra fields, we bring you: Blog extra fields!
Since we can't assign `post_author=0` directly in the post editor, we instead register a separate `ap_extrafield_blog` `post_type` for the Blog User.
I moved a bunch of stuff into an `Extra_Fields` class. This will come in handy for #788 😁 
1. Go to Settings -> ActivityPub -> Blog-Profile. 
2. The Extra Fields functionality should be there as shown above.
3. `curl -H 'Accept: application/activity+json' http://your.blog/@your.blog | jq .attachment` should reflect the state of the Blog Extra Fields. In the case of the screenshot above:
```json
[
{
"type": "PropertyValue",
"name": "Blog",
"value": "<p><a rel=\"me noopener\" title=\"http://wp.test/\" target=\"_blank\" href=\"http://wp.test/\">wp.test</a></p>"
},
{ …
```

Add Blog extra fields

---

activitypub.php

When the autoloader fails to find a class in the `Activipub\` namespace, it throws a `wp_die` but nothing in the error_log. Now it will do that, as well, to help poor hypothetical developers who have misspelled a class name (`ExtraFields` where it should have been `Extra_Fields`), possibly taking far too long to get to the bottom of it, theoretically…

Autoloader: log failure in addition to `wp_die()`

---

activitypub.php
includes/rest/class-interaction.php
integration/class-webfinger.php

implements #864
Adds the remote-reply feature to WebFinger using the OStatus reply feature `http://ostatus.org/schema/1.0/subscribe`.
Also adds a hook, so that maybe the Friends plugin can hook into the Remote-Follow feature:
`\do_action( 'activitypub_interactions_follow', $uri, $object );`
/cc @akirk

Simple Remote-Reply endpoint.

---

includes/transformer/class-post.php

This is more like an issue bug report with my status on what should happen.
The to attribute of a object like a Note/Post always contains the followers URL of the post author, even if they are not active.

Fix: wrong followers URL in "to" attribute of posts

---

includes/class-signature.php

When running in WordPress Playground with possibly imperfect OpenSSL support, it fatals like this:
```
Warning: openssl_pkey_export(): Cannot get key from parameter 1 in /var/www/html/wp-content/plugins/activitypub/includes/class-signature.php on line 98
Fatal error: Uncaught TypeError: openssl_pkey_get_details(): Argument #1 ($key) must be of type OpenSSLAsymmetricKey, bool given in /var/www/html/wp-content/plugins/activitypub/includes/class-signature.php:100 Stack trace: #0 /var/www/html/wp-content/plugins/activitypub/includes/class-signature.php(100): openssl_pkey_get_details(false) #1 /var/www/html/wp-content/plugins/activitypub/includes/class-signature.php(66): Activitypub\Signature::generate_key_pair_for(-1) #2 /var/www/html/wp-content/plugins/activitypub/includes/class-signature.php …
```

Be more defensive when openssl

---

assets/js/activitypub-header-image.js
templates/user-settings.php

I think I found a Core bug here. There's absolutely no reason for the ajax request to include `wp_customize=on`, the logic is entirely handled in the `wp_ajax_crop_image()` handler.
[This commit](https://github.com/WordPress/wordpress-develop/commit/9fe59ced578169572f00d14a065aed22da165cab) appears to have moved the logic from the Customizer into a more general purpose context while [leaving the constraining `wp_customize=on` parameter](https://github.com/WordPress/wordpress-develop/commit/9fe59ced578169572f00d14a065aed22da165cab#diff-ce553f4ec6128c3384da17e519b3b0390203c996681ef1413ecf4b600fac5673R25).
I guess this could be a core patch
Fixes #846
Make a custom controller but without `wp_customize=on`
1. Be logged in as an author-level user (or any other user who can create posts but not …

Header Images: fix cropping for users without the 'customize' capability
